spring:
  application:
    name: todo-proxy-service

eureka:
  instance:
    instance-id: todo-proxy-ms
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082