server:
  port: 8080

spring:
  application:
    name: gateway-service


eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: warn
    com.melardev: trace
    org.springframework.cloud.gateway: trace
